apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: auth-external
  namespace: api-auth
spec:
  organizationId: d899c2d7-c159-487d-947b-b4dc000da634
  secretName: auth-external
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: a2d77b61-0c6d-48f0-8606-b4dc000fe4fd
      secretKeyName: DB_URL
    - bwSecretId: 45ba224e-510d-4fb0-b2fe-b4dc0010208b
      secretKeyName: DB_USERNAME
    - bwSecretId: 9a5ca711-27cf-45a3-ada6-b4dc00104710
      secretKeyName: DB_PASSWORD
    - bwSecretId: a2fcc3d5-f9be-497b-92f9-b4dc0010696c
      secretKeyName: MONGODB_URI
    - bwSecretId: 3f63e0c9-1b71-4d68-99a4-b4dc001093db
      secretKeyName: MONGODB_DATABASE
    - bwSecretId: e52298dc-25fa-466b-81ca-b4dc0010b425
      secretKeyName: AUTH_JWT_ISSUER
    - bwSecretId: 2502d621-76a3-4f41-a4af-b4dc000f61d8
      secretKeyName: AUTH_JWT_PRIVATE_KEY_BASE64
    - bwSecretId: b4d6bb83-abdf-4861-bcad-b4dc000f9a13
      secretKeyName: AUTH_JWT_PUBLIC_KEY_BASE64
    - bwSecretId: 93d3b0c1-2614-449e-899a-b4dc0010f62c
      secretKeyName: AUTH_JWT_KEY_ID
    - bwSecretId: a88afdc6-347f-47c9-aedf-b4dc0011231d
      secretKeyName: AUTH_RATE_LIMIT_HMAC_KEY
