apiVersion: v1
kind: Service
metadata:
  name: api-auth
  namespace: api-auth
spec:
  type: ClusterIP
  selector:
    app: api-auth
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
