apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: core-external
  namespace: api-core
spec:
  organizationId: d899c2d7-c159-487d-947b-b4dc000da634
  secretName: core-external
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: be1f31a7-ea2a-4f63-b9b7-b4dc00a16f5f
      secretKeyName: DB_URL
    - bwSecretId: b9edbd00-9eb7-4bcf-a926-b4dc00a1dd01
      secretKeyName: DB_USERNAME
    - bwSecretId: 47d87ef5-9fda-4ca5-9b82-b4dc00a1ff1e
      secretKeyName: DB_PASSWORD
    - bwSecretId: e52298dc-25fa-466b-81ca-b4dc0010b425
      secretKeyName: AUTH_JWT_ISSUER
