apiVersion: v1
kind: Service
metadata:
  name: api-chatbot
  namespace: api-chatbot
spec:
  type: ClusterIP
  selector:
    app: api-chatbot
  ports:
    - name: http
      port: 80
      targetPort: http
