apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: chatbot-external
  namespace: api-chatbot
spec:
  organizationId: d899c2d7-c159-487d-947b-b4dc000da634
  secretName: chatbot-external
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: REPLACE_WITH_GEMINI_API_KEY_BITWARDEN_ID
      secretKeyName: GEMINI_API_KEY
    - bwSecretId: REPLACE_WITH_GROQ_API_KEY_BITWARDEN_ID
      secretKeyName: GROQ_API_KEY
    - bwSecretId: REPLACE_WITH_HF_TOKEN_BITWARDEN_ID
      secretKeyName: HF_TOKEN
    - bwSecretId: REPLACE_WITH_JWT_SECRET_BITWARDEN_ID
      secretKeyName: JWT_SECRET
    - bwSecretId: REPLACE_WITH_POSTGRES_DSN_BITWARDEN_ID
      secretKeyName: POSTGRES_DSN
    - bwSecretId: REPLACE_WITH_MONGODB_URI_BITWARDEN_ID
      secretKeyName: MONGODB_URI
    - bwSecretId: REPLACE_WITH_MONGODB_DB_BITWARDEN_ID
      secretKeyName: MONGODB_DB
    - bwSecretId: REPLACE_WITH_QDRANT_URL_BITWARDEN_ID
      secretKeyName: QDRANT_URL
    - bwSecretId: REPLACE_WITH_QDRANT_API_KEY_BITWARDEN_ID
      secretKeyName: QDRANT_API_KEY
    - bwSecretId: REPLACE_WITH_REDIS_URL_BITWARDEN_ID
      secretKeyName: REDIS_URL
