events {}
http {
  resolver kube-dns.kube-system.svc.cluster.local valid=10s;
  server {
    listen 8080;
    server_name AUTH_HOST;
    location / {
      set $upstream api-auth.api-auth.svc.cluster.local;
      proxy_pass http://$upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
  server {
    listen 8080;
    server_name CORE_HOST;
    location / {
      set $upstream api-core.api-core.svc.cluster.local;
      proxy_pass http://$upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
  server {
    listen 8080 default_server;
    server_name _;
    location = /edge-health { return 200 'ok'; }
    location / { return 404; }
  }
}
