name: Validate GKE Terraform

on:
  pull_request:
    paths:
      - '.github/workflows/terraform-gke-validate.yml'
      - 'terraform/gke/**'

jobs:
  validate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: terraform/gke
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: '1.11.4'
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false -input=false
      - run: terraform validate -no-color
